FROM mcr.microsoft.com/vscode/devcontainers/base:ubuntu-22.04
RUN sudo apt-get update && \
    sudo apt-get install -y \
        curl \
        g++ \
        libcairo2-dev \
        openjdk-8-jdk \
        pkg-config \
        python3-dev \
        python3-pip
